/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.40
 * Generated at: 2014-08-09 08:51:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class newAccount_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/css/newAccount.css\" />\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<title>회원가입</title>\r\n");
      out.write("\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\tfunction idFunc()\r\n");
      out.write("\t\t\t{\t\r\n");
      out.write("\t\t\t\tif(document.newRegister.userId.value.length<6)\r\n");
      out.write("\t\t\t\t{\t\r\n");
      out.write("\t\t\t\t\talert(\"아이디는 6자리 이상입니다.\");\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"userId\").value=\"\";\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"idIcon\").src=\"/images/newaccount/icon_red_check.jpg\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"idIcon\").src=\"/images/newaccount/icon_check.jpg\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tfunction passwordFunc()\r\n");
      out.write("\t\t\t{\t\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"checkRPass\").innerHTML=\"\";\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"rPassword\").value=\"\";\r\n");
      out.write("\t\t\t\tif(document.getElementById(\"uPassword\").value.length<6){\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"checkUPass\").innerHTML=\"6자리 이상\";\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"uPassIcon\").src=\"/images/newaccount/icon_red_check.jpg\";\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"rPassIcon\").src=\"/images/newaccount/icon_red_check.jpg\";\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"uPassIcon\").src=\"/images/newaccount/icon_check.jpg\";\r\n");
      out.write("\t\t\t\tif(document.getElementById(\"rPassword\").value!=\"\")\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"rPassIcon\").src=\"/images/newaccount/icon_red_check.jpg\";\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"rPassword\").value=\"\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tfunction repeatPasswordFunc()\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tif(document.getElementById(\"rPassword\").value!=document.getElementById(\"uPassword\").value){\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"rPassIcon\").src=\"/images/newaccount/icon_red_check.jpg\";\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"checkRPass\").innerHTML=\"다시 입력하세요.\"\r\n");
      out.write("\t\t\t\treturn;\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"rPassIcon\").src=\"/images/newaccount/icon_check.jpg\";\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"checkRPass\").innerHTML=\"\"\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tfunction checkName()\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tif(document.getElementById(\"uName\").value!=\"\")\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"uNameIcon\").src=\"/images/newaccount/icon_check.jpg\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"uNameIcon\").src=\"/images/newaccount/icon_red_check.jpg\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tfunction register()\r\n");
      out.write("\t\t\t{\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(document.getElementById(\"userId\").value!=\"\")\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tif(document.getElementById(\"rPassword\").value!=\"\")\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById(\"uName\").value!=\"\")\r\n");
      out.write("\t\t\t\t\t\t{\t\r\n");
      out.write("\t\t\t\t\t\t\tvar temp=\"\";\r\n");
      out.write("\t\t\t\t\t\t\ttemp+=\"ID :\"+document.getElementById(\"userId\").value+\"\\n\"\r\n");
      out.write("\t\t\t\t\t\t\t+\"PASS :\"+document.getElementById(\"rPassword\").value+\"\\n\"\r\n");
      out.write("\t\t\t\t\t\t\t+\"NAME :\"+document.getElementById(\"uName\").value+\"\\n\"\r\n");
      out.write("\t\t\t\t\t\t\t+\"EMAIL :\"+document.getElementById(\"email\").value+\"\\n\";\r\n");
      out.write("\t\t\t\t\t\t\ttemp+=\"TEL :\"\r\n");
      out.write("\t\t\t\t\t\t\tfor(var i=0;i<3;i++)\r\n");
      out.write("\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\tif(document.newRegister.tel[i].value!=\"\")\r\n");
      out.write("\t\t\t\t\t\t\t\ttemp+=document.newRegister.tel[i].value;\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\ttemp+=\"\\nPHONE :\";\r\n");
      out.write("\t\t\t\t\t\t\tfor(var i=0;i<3;i++)\r\n");
      out.write("\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\tif(document.newRegister.phone[i].value!=\"\")\r\n");
      out.write("\t\t\t\t\t\t\t\ttemp+=document.newRegister.phone[i].value;\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\ttemp+=\"\\nROUTE :\";\r\n");
      out.write("\t\t\t\t\t\t\tfor(var i=0;i<3;i++)\r\n");
      out.write("\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\tif(document.newRegister.route[i].checked)\r\n");
      out.write("\t\t\t\t\t\t\t\ttemp+=document.newRegister.route[i].value+\",\";\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\ttemp+=\"\\nINTRODUCE :\"+document.newRegister.introduce.value+\"\\n\";\r\n");
      out.write("\t\t\t\t\t\t\talert(temp);\r\n");
      out.write("\t\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\talert(\"체크항목을 모두 완성해 주세요\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfunction emailCheck(email)\r\n");
      out.write("\t\t\t{\t\r\n");
      out.write("\t\t\t\tif(email==\"\")\r\n");
      out.write("\t\t\t\t{\tdocument.getElementById(\"emailRequire\").innerHTML=\"주소를 입력하세요.\"\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"eMailIcon\").src=\"/images/newaccount/icon_red_check.jpg\";\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tvar fEmail = email.value.split('@');\r\n");
      out.write("\t\t\t\tif(fEmail.length!=2||fEmail[0]==\"\"||fEmail[1].split(\".\").length==1){\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"emailRequire\").innerHTML=\"잘못된 형식입니다.\"\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"eMailIcon\").src=\"/images/newaccount/icon_red_check.jpg\";\r\n");
      out.write("\t\t\t\t\treturn;\t\r\n");
      out.write("\t\t\t\t}\t/*첫번째 오류검사 형식이 맞지 않는 경우*/\r\n");
      out.write("\t\t\t\tfEmail = fEmail[1].split(\".\");\r\n");
      out.write("\t\t\t\tfor(var i=0;i<fEmail.length;i++)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tif(fEmail[i]==\"\")\r\n");
      out.write("\t\t\t\t\t{document.getElementById(\"emailRequire\").innerHTML=\"잘못된 형식입니다.\"\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"eMailIcon\").src=\"/images/newaccount/icon_red_check.jpg\";\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"emailRequire\").innerHTML=\"올바른 형식입니다.\"\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"eMailIcon\").src=\"/images/newaccount/icon_check.jpg\";\r\n");
      out.write("\t\t\t\treturn;\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t\t<div id=\"frame\">\r\n");
      out.write("\t\t<div id=\"header\"><p><img src=\"/images/newaccount/icon_check.jpg\" alt=\"필수\">은 필수 입력항목입니다.</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<form name=\"newRegister\" onsubmit=\"return register()\">\r\n");
      out.write("\t\t<table width=\"100%\" border=\"1\" cellspaceing=\"0\" cellpadding=\"0\" id=\"joinData\" summary=\"총 10개의 입력항목\">\r\n");
      out.write("\t\t<tbody>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th class=\"inputKind\"><img id=\"idIcon\" src=\"/images/newaccount/icon_red_check.jpg\" alt=\"필수\"><label>아이디</label></th>\r\n");
      out.write("\t\t\t\t<th class=\"inputData\"><input type=\"text\" id=\"userId\" onchange= \"return idFunc()\"/></th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th class=\"inputKind\"><img id=\"uPassIcon\" src=\"/images/newaccount/icon_red_check.jpg\" alt=\"필수\"><label>비밀번호</label></th>\r\n");
      out.write("\t\t\t\t<th class=\"inputData\"><input type=\"password\" id=\"uPassword\" onchange=\"return passwordFunc();\"/><label id=\"checkUPass\"></label></th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th class=\"inputKind\"><img id=\"rPassIcon\" src=\"/images/newaccount/icon_red_check.jpg\" alt=\"필수\"><label>비밀번호 확인</label></th>\r\n");
      out.write("\t\t\t\t<th class=\"inputData\"><input type=\"password\" id=\"rPassword\"onchange=\"return repeatPasswordFunc();\"/><label id=\"checkRPass\"></label></th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th class=\"inputKind\"><img id=\"uNameIcon\"src=\"/images/newaccount/icon_red_check.jpg\" alt=\"필수\">\r\n");
      out.write("\t\t\t\t<label>이름</label></th>\r\n");
      out.write("\t\t\t\t<th class=\"inputData\"><input type=\"text\" id=\"uName\" onchange=\"return checkName();\"/></th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th class=\"inputKind\"><img id=\"eMailIcon\" src=\"/images/newaccount/icon_red_check.jpg\" alt=\"필수\"><label>이메일</label></th>\r\n");
      out.write("\t\t\t\t<th class=\"inputData\"><input type=\"text\" id=\"email\" onchange=\"return emailCheck(this)\"/><label id=\"emailRequire\">주소를 입력하세요.</label></th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th class=\"inputKind\"><label>전화번호</label></th>\r\n");
      out.write("\t\t\t\t<th class=\"inputData\"><input type=\"text\"  name=\"tel\" maxlength=\"3\" size=\"3\" />\r\n");
      out.write("\t\t\t\t\t-<input type=\"text\" name=\"tel\" maxlength=\"4\" size=\"4\" />\r\n");
      out.write("\t\t\t\t\t-<input type=\"text\" name=\"tel\" maxlength=\"4\" size=\"4\" />\r\n");
      out.write("\t\t\t\t</th>\r\n");
      out.write("\t\t\t</tr>\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th class=\"inputKind\"><label>휴대폰</label></th>\r\n");
      out.write("\t\t\t\t<th class=\"inputData\"><input type=\"text\"  name=\"phone\" maxlength=\"3\" size=\"3\"/>\r\n");
      out.write("\t\t\t\t\t-<input type=\"text\" name=\"phone\" maxlength=\"4\" size=\"4\"/>\r\n");
      out.write("\t\t\t\t\t-<input type=\"text\" name=\"phone\" maxlength=\"4\" size=\"4\"/></th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th class=\"inputKind\"><label>이메일 수신</label></th>\r\n");
      out.write("\t\t\t\t<th class=\"inputData\"><input type=\"checkbox\" name=\"route\" value=\"notice\"/><label>공지사항</label>\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" name=\"route\" value=\"news\"/><label>소식</label>\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" name=\"route\" value=\"event\"/>이벤트</th>\r\n");
      out.write("\t\t\t</tr>\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th class=\"inputKind\"><label>자기소개</label></th>\r\n");
      out.write("\t\t\t\t<th class=\"inputData\"><input type=\"text\" name=\"introduce\"class=\"info\"/></th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th><input class=\"sButton\" type=\"submit\" value=\"회원가입\" /></th>\r\n");
      out.write("\t\t\t\t<th><input class=\"sButton\" type=\"reset\" value='취소하기'/></th>\r\n");
      out.write("\t\t\t</tr>\t\t\r\n");
      out.write("\t\t</tbody>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
