/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.40
 * Generated at: 2014-08-12 09:12:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class status_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html lang=\"ko\" xmlns:v=\"urn:schemas-microsoft-com:vml\">\r\n");
      out.write("<head>\r\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("        <title>ìíì½ë</title>\r\n");
      out.write("        \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://openapi.map.naver.com/openapi/naverMap.naver?ver=2.0&key=806edb60b7778c1e58ea03b83f3bba5a\"></script>\r\n");
      out.write("<div id=\"map\" style=\"border:1px solid #000;\"></div>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("                var oSeoulCityPoint = new nhn.api.map.LatLng(37.5675451, 126.9773356);\r\n");
      out.write("                var defaultLevel = 11;\r\n");
      out.write("                var oMap = new nhn.api.map.Map(document.getElementById('map'), { \r\n");
      out.write("                                                point : oSeoulCityPoint,\r\n");
      out.write("                                                zoom : defaultLevel,\r\n");
      out.write("                                                enableWheelZoom : true,\r\n");
      out.write("                                                enableDragPan : true,\r\n");
      out.write("                                                enableDblClickZoom : false,\r\n");
      out.write("                                                mapMode : 0,\r\n");
      out.write("                                                activateTrafficMap : false,\r\n");
      out.write("                                                activateBicycleMap : false,\r\n");
      out.write("                                                minMaxLevel : [ 1, 14 ],\r\n");
      out.write("                                                size : new nhn.api.map.Size(800, 480)           });\r\n");
      out.write("                var oSlider = new nhn.api.map.ZoomControl();\r\n");
      out.write("                oMap.addControl(oSlider);\r\n");
      out.write("                oSlider.setPosition({\r\n");
      out.write("                        top : 10,\r\n");
      out.write("                        left : 10\r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("                var oMapTypeBtn = new nhn.api.map.MapTypeBtn();\r\n");
      out.write("                oMap.addControl(oMapTypeBtn);\r\n");
      out.write("                oMapTypeBtn.setPosition({\r\n");
      out.write("                        bottom : 10,\r\n");
      out.write("                        right : 80\r\n");
      out.write("                });\r\n");
      out.write("                \r\n");
      out.write("                var oThemeMapBtn = new nhn.api.map.ThemeMapBtn();\r\n");
      out.write("                oThemeMapBtn.setPosition({\r\n");
      out.write("                        bottom : 10,\r\n");
      out.write("                        right : 10\r\n");
      out.write("                });\r\n");
      out.write("                oMap.addControl(oThemeMapBtn);\r\n");
      out.write("\r\n");
      out.write("                var oBicycleGuide = new nhn.api.map.BicycleGuide(); // - ìì ê±° ë²ë¡ ì ì¸\r\n");
      out.write("                oBicycleGuide.setPosition({\r\n");
      out.write("                        top : 10,\r\n");
      out.write("                        right : 10\r\n");
      out.write("                }); // - ìì ê±° ë²ë¡ ìì¹ ì§ì \r\n");
      out.write("                oMap.addControl(oBicycleGuide);// - ìì ê±° ë²ë¡ë¥¼ ì§ëì ì¶ê°.\r\n");
      out.write("\r\n");
      out.write("                var oTrafficGuide = new nhn.api.map.TrafficGuide(); // - êµíµ ë²ë¡ ì ì¸\r\n");
      out.write("                oTrafficGuide.setPosition({\r\n");
      out.write("                        bottom : 30,\r\n");
      out.write("                        left : 10\r\n");
      out.write("                });  // - êµíµ ë²ë¡ ìì¹ ì§ì .\r\n");
      out.write("                oMap.addControl(oTrafficGuide); // - êµíµ ë²ë¡ë¥¼ ì§ëì ì¶ê°.\r\n");
      out.write("\r\n");
      out.write("                var trafficButton = new nhn.api.map.TrafficMapBtn(); // - ì¤ìê° êµíµì§ë ë²í¼ ì ì¸\r\n");
      out.write("                trafficButton.setPosition({\r\n");
      out.write("                        bottom:10, \r\n");
      out.write("                        right:150\r\n");
      out.write("                }); // - ì¤ìê° êµíµì§ë ë²í¼ ìì¹ ì§ì \r\n");
      out.write("                oMap.addControl(trafficButton);\r\n");
      out.write("\r\n");
      out.write("                var oSize = new nhn.api.map.Size(28, 37);\r\n");
      out.write("                var oOffset = new nhn.api.map.Size(14, 37);\r\n");
      out.write("                var oIcon = new nhn.api.map.Icon('http://static.naver.com/maps2/icons/pin_spot2.png', oSize, oOffset);\r\n");
      out.write("\r\n");
      out.write("                var oInfoWnd = new nhn.api.map.InfoWindow();\r\n");
      out.write("                oInfoWnd.setVisible(false);\r\n");
      out.write("                oMap.addOverlay(oInfoWnd);\r\n");
      out.write("\r\n");
      out.write("                oInfoWnd.setPosition({\r\n");
      out.write("                        top : 20,\r\n");
      out.write("                        left :20\r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("                var oLabel = new nhn.api.map.MarkerLabel(); // - ë§ì»¤ ë¼ë²¨ ì ì¸.\r\n");
      out.write("                oMap.addOverlay(oLabel); // - ë§ì»¤ ë¼ë²¨ ì§ëì ì¶ê°. ê¸°ë³¸ì ë¼ë²¨ì´ ë³´ì´ì§ ìë ìíë¡ ì¶ê°ë¨.\r\n");
      out.write("\r\n");
      out.write("                oInfoWnd.attach('changeVisible', function(oCustomEvent) {\r\n");
      out.write("                        if (oCustomEvent.visible) {\r\n");
      out.write("                                oLabel.setVisible(false);\r\n");
      out.write("                        }\r\n");
      out.write("                });\r\n");
      out.write("                \r\n");
      out.write("                var oPolyline = new nhn.api.map.Polyline([], {\r\n");
      out.write("                        strokeColor : '#f00', // - ì ì ìê¹\r\n");
      out.write("                        strokeWidth : 5, // - ì ì ëê»\r\n");
      out.write("                        strokeOpacity : 0.5 // - ì ì í¬ëªë\r\n");
      out.write("                }); // - polyline ì ì¸, ì²«ë²ì§¸ ì¸ìë ì ì´ ê·¸ë ¤ì§ ì ì ìì¹. íì¬ë ìì.\r\n");
      out.write("                oMap.addOverlay(oPolyline); // - ì§ëì ì ì ì¶ê°í¨.\r\n");
      out.write("\r\n");
      out.write("                oMap.attach('mouseenter', function(oCustomEvent) {\r\n");
      out.write("\r\n");
      out.write("                        var oTarget = oCustomEvent.target;\r\n");
      out.write("                        // ë§ì»¤ìì ë§ì°ì¤ ì¬ë¼ê°ê±°ë©´\r\n");
      out.write("                        if (oTarget instanceof nhn.api.map.Marker) {\r\n");
      out.write("                                var oMarker = oTarget;\r\n");
      out.write("                                oLabel.setVisible(true, oMarker); // - í¹ì  ë§ì»¤ë¥¼ ì§ì íì¬ í´ë¹ ë§ì»¤ì titleì ë³´ì¬ì¤ë¤.\r\n");
      out.write("                        }\r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("                oMap.attach('mouseleave', function(oCustomEvent) {\r\n");
      out.write("\r\n");
      out.write("                        var oTarget = oCustomEvent.target;\r\n");
      out.write("                        // ë§ì»¤ììì ë§ì°ì¤ ëê°ê±°ë©´\r\n");
      out.write("                        if (oTarget instanceof nhn.api.map.Marker) {\r\n");
      out.write("                                oLabel.setVisible(false);\r\n");
      out.write("                        }\r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("                oMap.attach('click', function(oCustomEvent) {\r\n");
      out.write("                        var oPoint = oCustomEvent.point;\r\n");
      out.write("                        var oTarget = oCustomEvent.target;\r\n");
      out.write("                        oInfoWnd.setVisible(false);\r\n");
      out.write("                        // ë§ì»¤ í´ë¦­íë©´\r\n");
      out.write("                        if (oTarget instanceof nhn.api.map.Marker) {\r\n");
      out.write("                                // ê²¹ì¹¨ ë§ì»¤ í´ë¦­íê±°ë©´\r\n");
      out.write("                                if (oCustomEvent.clickCoveredMarker) {\r\n");
      out.write("                                        return;\r\n");
      out.write("                                }\r\n");
      out.write("                                // - InfoWindow ì ë¤ì´ê° ë´ì©ì setContent ë¡ ìì ë¡­ê² ë£ì ì ììµëë¤. ì¸ë¶ cssë¥¼ ì´ì©í  ì ìì¼ë©°, \r\n");
      out.write("                                // - ì¸ë¶ cssì ì ì¸ë classë¥¼ ì´ì©íë©´ í´ë¹ classì ì¤íì¼ì ë°ë¡ ì ì©í  ì ììµëë¤.\r\n");
      out.write("                                // - ë¨, DIV ì position style ì absolute ê° ëë©´ ìëë©°, \r\n");
      out.write("                                // - absolute ì ê²½ì° autoPosition ì´ ëìíì§ ììµëë¤. \r\n");
      out.write("                                oInfoWnd.setContent('<DIV style=\"border-top:1px solid; border-bottom:2px groove black; border-left:1px solid; border-right:2px groove black;margin-bottom:1px;color:black;background-color:white; width:auto; height:auto;\">'+\r\n");
      out.write("                                        '<span style=\"color: #000000 !important;display: inline-block;font-size: 12px !important;font-weight: bold !important;letter-spacing: -1px !important;white-space: nowrap !important; padding: 2px 5px 2px 2px !important\">' + \r\n");
      out.write("                                        'Hello World <br /> ' + oTarget.getPoint()\r\n");
      out.write("                                        +'<span></div>');\r\n");
      out.write("                                oInfoWnd.setPoint(oTarget.getPoint());\r\n");
      out.write("                                oInfoWnd.setPosition({right : 15, top : 30});\r\n");
      out.write("                                oInfoWnd.setVisible(true);\r\n");
      out.write("                                oInfoWnd.autoPosition();\r\n");
      out.write("                                return;\r\n");
      out.write("                        }\r\n");
      out.write("                        var oMarker = new nhn.api.map.Marker(oIcon, { title : 'ë§ì»¤ : ' + oPoint.toString() });\r\n");
      out.write("                        oMarker.setPoint(oPoint);\r\n");
      out.write("                        oMap.addOverlay(oMarker);\r\n");
      out.write("\r\n");
      out.write("                        var aPoints = oPolyline.getPoints(); // - íì¬ í´ë¦¬ë¼ì¸ì ì´ë£¨ë ì ì ê°ì ¸ìì ë°°ì´ì ì ì¥.\r\n");
      out.write("                        aPoints.push(oPoint); // - ì¶ê°íê³ ì íë ì ì ì¶ê°íì¬ ë°°ì´ë¡ ì ì¥í¨.\r\n");
      out.write("                        oPolyline.setPoints(aPoints); // - í´ë¹ í´ë¦¬ë¼ì¸ì ë°°ì´ì ì ì¥ë ì ì ì¶ê°í¨\r\n");
      out.write("                });\r\n");
      out.write("        </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("                 ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
