/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.40
 * Generated at: 2014-08-21 03:14:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class newADV_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/css/newADV.css\" />\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\twindow.onload = function(){\r\n");
      out.write("\t\r\n");
      out.write("\t\t\tvar usercheck = document.getElementById(\"requestID\").value;\r\n");
      out.write("\t\t\tvar advcheck = document.getElementById(\"advID\").value;\r\n");
      out.write("\t\tif(usercheck == \"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert(\"로그인해주세요!\");\r\n");
      out.write("\t\t\twindow.location.assign(\"login\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if(advcheck ==\"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert(\"디지털 사이니지를 선택해주세요\");\r\n");
      out.write("\t\t\twindow.location.assign(\"regist\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"frame\">\r\n");
      out.write("\t\t<div class =\"newADVTable\">\r\n");
      out.write("\t\t<form name=\"newADVReuslt\" action=\"newADVResult\" method=\"post\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"signageID\" id=\"signageID\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${signageID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("\t\t<table width=\"100%\" border=\"1\"  cellpadding=\"0\" id=\"joinData\" summary=\"총 10개의 입력항목\">\r\n");
      out.write("\t\t<tbody>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"inputKind\"><label>신청자</label></td>\r\n");
      out.write("\t\t\t\t<td class=\"inputData\"><input type=\"text\" name=\"requestID\" id = \"requestID\" readonly=\"readonly\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.logininfo.userId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" /></td>\t\r\n");
      out.write("\t\t\t</tr>\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"inputKind\"><label>위치</label></td>\r\n");
      out.write("\t\t\t\t<td class=\"inputData\"><input type=\"text\" name=\"signageLocate\" id=\"signageLocate\" readonly=\"readonly\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${signageName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" /></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"inputKind\"><label>광고명</label></td>\r\n");
      out.write("\t\t\t\t<td class=\"inputData\"><input type=\"text\" name=\"advName\" id = \"advName\"  /></td>\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"inputKind\"><label>광고종류</label></td>\r\n");
      out.write("\t\t\t\t<td class=\"inputData\"><input type=\"radio\" name=\"advKind\" value=\"V\" checked=\"checked\"/><label>영상</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <input type=\"radio\" name=\"advKind\" value=\"P\"/><label>사진</label>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"inputKind\"><label>원하는 고객종류</label></td>\r\n");
      out.write("\t\t\t\t<td class=\"inputData\"><input type=\"radio\" name=\"peopleKind\" value=\"M\"/><label>남성</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <input type=\"radio\" name=\"peopleKind\" value=\"W\"/><label>여성</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <input type=\"radio\" name=\"peopleKind\" value=\"N\" checked=\"checked\"/><label>무관</label></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"inputKind\">\r\n");
      out.write("\t\t\t\t<label>원하는 사람 수</label></td>\r\n");
      out.write("\t\t\t\t<td class=\"inputData\"><input type=\"text\" name=\"peopleNum\"/></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"inputKind\">\r\n");
      out.write("\t\t\t\t<label>파일</label></td>\r\n");
      out.write("\t\t\t\t<td class=\"inputData\"><input type=\"file\" name=\"filelocate\"/></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t<td><input class=\"sButton\" type=\"submit\" value=\"회원가입\" /></td>\r\n");
      out.write("\t\t\t</tr>\t\t\r\n");
      out.write("\t\t</tbody>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
